### ISSUE TITLE
Anamorphic SBS aspect ratio error

### ISSUE THREAD

**Issue by 2018robert** [TimoWilhelm/vr-player#3]
Anamorphic videos SBS video displays in 3D in the headset (thanks!) but the aspect ratio is wrong, as if stretched veritcally.

**Comment by TimoWilhelm** [comment]
The app supports screen (flat), 180° or 360° video files. It tries to automatically detect the format but sometimes this doesn't work and you need to select the option manually.

Unfortunately there are currently no in-VR controls so you need to select the options in the browser window.

If that doesn't help I'd need to take a look at the video file you're trying to play.
